[Code/CppStandard] Massive cleanup warnings (#388)
* Warnings cleanup and modernize code

* Massive warning removal

* Massive warning purge

* Warning purge AND fixed script flag assignement wrong

* Revert all context used + warnings purge => compiled ok

* Boost deprecated warning

* PathGenerator warning clean

* More warning removal

* Boost 1.87 deprecated fix

* Boost 1.87 include removed for later

* Unused include removal + more warnings cleaning

* More warnings

* Includes

* Last includes

* Fix for GCC workflow:
/home/runner/work/Legends-of-Azeroth-Pandaria-5.4.8/Legends-of-Azeroth-Pandaria-5.4.8/src/server/game/Handlers/NPCHandler.cpp:500:65: error: invalid use of incomplete type ‘class CreatureAI’
  500 |     if (!sScriptMgr->OnGossipHello(_player, unit) && !unit->AI()->OnGossipHello(_player))
      |                                                                 ^~

---------

Co-authored-by: antony <antony.entringer@avmup.com>